spring :
  datasource :
    url : jdbc:mysql://localhost:3306/db_name
    username : (DB User Name)
    password : (DB Password)
  jpa :
    properties :
      hibernate :
        format_sql:true
    show-sql : true
    hibernate :
      ddl-auto : update
      # ddl-auto - @Entity 테이블 정보를 실제 DB에 반영 할건지 설정(create/update/none..)